url: "http://celiefavre.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false

kramdown:
   input: GFM


permalink: /:year/:month/:day/:title/

comments: true

exclude: [node_modules, gulpfile.js, package.json, gemfile, Gemfile.lock]

prose:
  rooturl: '_posts'
  siteurl: 'http://www.psy-emdr.com'
  ignore: ['_config.yml', '/_layouts', '/_includes']
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "text"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "tags"
        field:
          element: 'multiselect'
          label: 'ajouter un tag'
          placeholder: 'choisis un tag'
          options:
           - name: 'EMDR'
             value: 'emdr'
           - name: 'Psychologie'
             value: 'psychologie'